package com.jxl.ai.intelliconf.toolkit;

import com.jxl.ai.intelliconf.dao.entity.ConfMilestoneDO;
import com.jxl.ai.intelliconf.enums.MilestoneTemplate;
import org.springframework.stereotype.Component;

import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.stream.Collectors;

@Component
public class MilestoneUtil {

    public List<ConfMilestoneDO> generateDefaultTimeline(Long conferenceId, Date confStartTime) {
        List<ConfMilestoneDO> milestones = Arrays.stream(MilestoneTemplate.values()).map(template -> {
            ConfMilestoneDO milestone = new ConfMilestoneDO();
            milestone.setConfereId(conferenceId);
            milestone.setNodeCode(template.getCode());
            milestone.setNodeName(template.getName());
            milestone.setPreNodeCode(template.getPreNode());
            milestone.setStartDate(calculateDate(confStartTime, template.getStartOffset()));
            milestone.setTargetEndDate(calculateDate(confStartTime, template.getEndOffset()));
            milestone.setStatus(0);
            milestone.setIsConfirmed(0);
            milestone.setSortOrder(template.ordinal() + 1);
            milestone.setIsRequired(1);
            milestone.setAutoGenerateTasks(1);
            milestone.setRemark("System auto-generated by template.");
            return milestone;
        }).collect(Collectors.toList());

        for (int i = 0; i < milestones.size() - 1; i++) {
            ConfMilestoneDO current = milestones.get(i);
            ConfMilestoneDO next = milestones.get(i + 1);
            int dayGap = MilestoneTemplate.LOGISTICS.getCode().equals(current.getNodeCode())
                    && MilestoneTemplate.CONFERENCE.getCode().equals(next.getNodeCode()) ? 7 : 1;
            current.setTargetEndDate(addDays(next.getStartDate(), -dayGap));
        }

        return milestones;
    }

    private Date calculateDate(Date baseDate, int dayOffset) {
        if (baseDate == null) {
            return null;
        }
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(baseDate);
        calendar.add(Calendar.DAY_OF_YEAR, dayOffset);
        return calendar.getTime();
    }

    private Date addDays(Date baseDate, int dayOffset) {
        if (baseDate == null) {
            return null;
        }
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(baseDate);
        calendar.add(Calendar.DAY_OF_YEAR, dayOffset);
        return calendar.getTime();
    }
}
